### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by piotrd** [paulyoung/jade-inheritance#11]
Hi,

Could you please update dependencies of your project?

**Comment by paulyoung** [comment]
Hi @piotrd 

Could you be more specific? Perhaps a pull request would be the best way to communicate the changes you have in mind.

**Comment by piotrd** [comment]
Hi @paulyoung,

Sorry, I was in a hurry, but didn't want to forget about notifying you. I'm getting this:

`npm WARN unmet dependency [...]/node_modules/gulp-jade-inheritance/node_modules/jade-inheritance requires jade@'~1.9.2' but will load`

The latest jade, which I have installed, is now 1.11.0. The above warning is caused by outdated jade in jade-inheritance, am I right?

**Comment by paulyoung** [comment]
What are you doing to present that warning? Could you provide steps to reproduce?

**Comment by piotrd** [comment]
Steps to reproduce: have your package.npm include `"jade": "^1.11.0"` in `dependencies`, plus any package that depends on an earlier jade, e.g. `gulp-jade-inheritance`, which I use. Any `npm` command call will trigger this warning.

**Comment by piotrd** [comment]
@paulyoung weird, you know. I did `npm prune`, cleared `node_modules` dir, installed all modules again and the warning is gone. Sorry for the inconvenience. Let's close this thread.

**Comment by paulyoung** [comment]
Thanks @piotrd!
