### ISSUE TITLE
A bug in dependent package character-parser cause error when using relative file path

### ISSUE THREAD

**Issue by woodpig07** [paulyoung/jade-inheritance#9]
Hello Paul,
It looks jade-inheritance depends on jade@~0.34.1, which depends on character-parser@1.0.2.
I believe there is a bug in that version so that jade-inheritance keeps failing when input filename has relative path, for example:
![screen shot 2014-11-13 at 2 12 53 pm](https://cloud.githubusercontent.com/assets/4519861/5024152/b19ee33a-6b40-11e4-8dee-db3ec0d23398.png)

I tried to update character-parser to latest version 1.2.0, then the problem solved.
Would you considering upgrade your package with latest version of jade?

Thanks

**Comment by paulyoung** [comment]
I'd prefer to have a test suite in place before making any changes, just to confirm that there are no regressions.

I have considered changing the API to require an instance of Jade to be provided by consumers, but  without tests hard to say which versions are supported.

**Comment by paulyoung** [comment]
Jade was updated a while back, so I'm closing this one. Thanks @woodpig07!
